### ISSUE TITLE
What's the advantage to using this?

### ISSUE THREAD

**Issue by laserbeak** [Cozza38/docker-pCars2Server#1]
What's the advantage to using this over the provided  server?

**Comment by Cozza38** [comment]
Hey there, in what regards?

This project is just the provided server wrapped up into a docker container. I use this personally on unraid and found that the docker holding the files was a little easier with unraid docker implementation.

If your concerned about the server files being modified, you can replace them with your own and everything will work. You can also check the md5 of mine against a fresh download and I expect them to be the same
